# Generated by Django 3.0.8 on 2020-12-24 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201221_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postsliked',
            field=models.ManyToManyField(blank=True, related_name='likedposts', to='network.Posts'),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
